version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ct-user-api:latest
    env_file:
      - .env
    environment:
      - PORT=5000
    ports:
      - "${PORT}:${PORT}"
